import type {
  Agent,
  ActivityEntry,
  DataFeasibilityAssessment,
  FeasibilityScore,
  FeasibilityWeights,
  Milestone,
  MilestoneStatus,
  PortfolioConfig,
  Risk,
  ROIAuditEntry,
  ROIMethodology,
  ROITarget,
  MeasuredOutcome,
  AdoptionMetrics,
} from './types';
import {
  saveAgent,
  savePortfolioConfig,
  saveDataFeasibility,
  saveROIMethodology,
  appendROIAuditEntry,
  appendActivityEntry,
  getAgentCount,
} from './storage';

// ─── Default weights ──────────────────────────────────────────────────────────

const DEFAULT_WEIGHTS: FeasibilityWeights = {
  dataReadiness: 0.25,
  modelMaturity: 0.15,
  buildComplexity: 0.10,
  adoptionReadiness: 0.20,
  changeMgmtScope: 0.15,
  politicalViability: 0.15,
};

// ─── Helper builders ──────────────────────────────────────────────────────────

function score(
  dr: 1|2|3|4|5, mm: 1|2|3|4|5, bc: 1|2|3|4|5,
  ar: 1|2|3|4|5, cm: 1|2|3|4|5, pv: 1|2|3|4|5,
  scoredBy: string, scoredAt: string, notes: string
): FeasibilityScore {
  const w = DEFAULT_WEIGHTS;
  const composite = dr*w.dataReadiness + mm*w.modelMaturity + bc*w.buildComplexity
    + ar*w.adoptionReadiness + cm*w.changeMgmtScope + pv*w.politicalViability;
  return { dataReadiness: dr, modelMaturity: mm, buildComplexity: bc,
    adoptionReadiness: ar, changeMgmtScope: cm, politicalViability: pv,
    composite: Math.round(composite * 100) / 100, weights: { ...DEFAULT_WEIGHTS },
    scoredAt, scoredBy, notes };
}

function ms(id: string, title: string, dueDate: string, status: MilestoneStatus,
  owner: string, notes = '', completedDate?: string): Milestone {
  return { id, title, dueDate, status, owner, notes, completedDate };
}

function risk(id: string, description: string, severity: Risk['severity'],
  likelihood: Risk['likelihood'], mitigation: string, owner: string,
  status: Risk['status'] = 'open'): Risk {
  return { id, description, severity, likelihood, mitigation, owner, status };
}

function roiTarget(
  id: string, category: ROITarget['category'], metric: string,
  unit: ROITarget['unit'], baseline: number, target: number, targetDate: string,
  formula: string, params: Record<string, number>, method: string,
  cfoApproved: boolean, approvedDate?: string, killThreshold?: number,
  controlCohort?: string
): ROITarget {
  return { id, category, metric, unit, baselineValue: baseline, targetValue: target,
    targetDate, monetizationFormula: formula, monetizationParams: params,
    measurementMethod: method, cfoApproved, approvedDate, killThreshold,
    controlCohort };
}

function outcome(
  id: string, roiTargetId: string, measuredAt: string, measuredValue: number,
  monetizedValue: number, source: string, validatedBy?: string,
  dataExportVersion?: string, notes = ''
): MeasuredOutcome {
  return { id, roiTargetId, measuredAt, measuredValue, monetizedValue, source,
    validatedBy, validatedAt: validatedBy ? measuredAt : undefined,
    dataExportVersion, notes };
}

// ─── Portfolio Config ─────────────────────────────────────────────────────────

export const SEED_CONFIG: PortfolioConfig = {
  fiscalYearStart: '2026-01-01',
  functions: [
    { id: 'fn-sales', name: 'Sales', leader: 'TBD', defaultHourlyRate: 95,
      affectedPopulation: 250, budgetAllocation: 50 },
    { id: 'fn-mktg', name: 'Marketing', leader: 'TBD', defaultHourlyRate: 85,
      affectedPopulation: 80, budgetAllocation: 25 },
    { id: 'fn-cs', name: 'Customer Success', leader: 'TBD', defaultHourlyRate: 90,
      affectedPopulation: 120, budgetAllocation: 25 },
  ],
  defaultFeasibilityWeights: { ...DEFAULT_WEIGHTS },
  defaultPrioritizationWeights: {
    expectedRoi: 0.35, feasibility: 0.30, strategicAlignment: 0.15,
    timeToValue: 0.10, riskAdjusted: 0.10,
  },
  cfoApprovalRequired: true,
  totalProgramBudget: { year1: 16_000_000, year2: 24_000_000, year3: 20_000_000 },
};

// ─── Adoption helpers ─────────────────────────────────────────────────────────

function s1Adoption(): AdoptionMetrics {
  return {
    agentId: 'agent-s1',
    targetPopulation: 250,
    activeUsers: 215,
    weeklyActiveUsers: 195,
    usageFrequency: 4.2,
    satisfactionScore: 4.1,
    byFunction: [{ function: 'Sales', activeUsers: 215, targetUsers: 250 }],
    byRegion: [
      { region: 'Americas', activeUsers: 132, targetUsers: 155 },
      { region: 'EMEA', activeUsers: 57, targetUsers: 65 },
      { region: 'APAC', activeUsers: 26, targetUsers: 30 },
    ],
    byRole: [
      { role: 'Account Executive', activeUsers: 165, targetUsers: 190 },
      { role: 'Sales Manager', activeUsers: 35, targetUsers: 42 },
      { role: 'SDR', activeUsers: 15, targetUsers: 18 },
    ],
    trend: [
      { weekStarting: '2025-10-20', activeUsers: 48, weeklyActive: 42 },
      { weekStarting: '2025-10-27', activeUsers: 78, weeklyActive: 70 },
      { weekStarting: '2025-11-03', activeUsers: 105, weeklyActive: 95 },
      { weekStarting: '2025-11-10', activeUsers: 130, weeklyActive: 118 },
      { weekStarting: '2025-11-17', activeUsers: 148, weeklyActive: 134 },
      { weekStarting: '2025-11-24', activeUsers: 158, weeklyActive: 144 },
      { weekStarting: '2025-12-01', activeUsers: 168, weeklyActive: 152 },
      { weekStarting: '2025-12-08', activeUsers: 178, weeklyActive: 160 },
      { weekStarting: '2025-12-15', activeUsers: 185, weeklyActive: 168 },
      { weekStarting: '2025-12-22', activeUsers: 188, weeklyActive: 170 },
      { weekStarting: '2026-01-05', activeUsers: 195, weeklyActive: 176 },
      { weekStarting: '2026-01-12', activeUsers: 208, weeklyActive: 188 },
      { weekStarting: '2026-04-27', activeUsers: 215, weeklyActive: 195 },
    ],
    lastUpdated: '2026-05-01',
  };
}

function c1Adoption(): AdoptionMetrics {
  return {
    agentId: 'agent-c1',
    targetPopulation: 120,
    activeUsers: 108,
    weeklyActiveUsers: 98,
    usageFrequency: 6.8,
    satisfactionScore: 3.9,
    byFunction: [{ function: 'Customer Success', activeUsers: 108, targetUsers: 120 }],
    byRegion: [
      { region: 'Americas', activeUsers: 68, targetUsers: 75 },
      { region: 'EMEA', activeUsers: 28, targetUsers: 32 },
      { region: 'APAC', activeUsers: 12, targetUsers: 13 },
    ],
    byRole: [
      { role: 'CSM', activeUsers: 72, targetUsers: 80 },
      { role: 'Technical Account Manager', activeUsers: 28, targetUsers: 32 },
      { role: 'CS Manager', activeUsers: 8, targetUsers: 8 },
    ],
    trend: [
      { weekStarting: '2025-12-08', activeUsers: 35, weeklyActive: 30 },
      { weekStarting: '2025-12-15', activeUsers: 55, weeklyActive: 48 },
      { weekStarting: '2025-12-22', activeUsers: 68, weeklyActive: 60 },
      { weekStarting: '2025-12-29', activeUsers: 72, weeklyActive: 64 },
      { weekStarting: '2026-01-05', activeUsers: 80, weeklyActive: 72 },
      { weekStarting: '2026-01-12', activeUsers: 85, weeklyActive: 76 },
      { weekStarting: '2026-01-19', activeUsers: 90, weeklyActive: 82 },
      { weekStarting: '2026-01-26', activeUsers: 95, weeklyActive: 86 },
      { weekStarting: '2026-02-02', activeUsers: 98, weeklyActive: 89 },
      { weekStarting: '2026-02-09', activeUsers: 102, weeklyActive: 92 },
      { weekStarting: '2026-02-16', activeUsers: 105, weeklyActive: 95 },
      { weekStarting: '2026-02-23', activeUsers: 106, weeklyActive: 96 },
      { weekStarting: '2026-04-27', activeUsers: 108, weeklyActive: 98 },
    ],
    lastUpdated: '2026-05-01',
  };
}

// ─── Agents ───────────────────────────────────────────────────────────────────

export const SEED_AGENTS: Agent[] = [

  // ── E1: GTM AI Academy (Tier 0) ──────────────────────────────────────────
  {
    id: 'agent-e1',
    code: 'E1',
    name: 'GTM AI Academy',
    description: 'Cross-functional enablement program that trains all GTM roles on AI tools, workflows, and responsible use — the foundation every other agent depends on.',
    function: 'cross_functional',
    type: 'hybrid',
    tier: 'tier_0_foundation',
    stage: 'production',
    buildBuyDecision: 'hybrid',
    vendor: 'Internal + Coursera',
    owner: 'Academy Lead',
    ownerFunction: 'GTM Transformation',
    cdioPartner: 'VP, Digital Enablement',
    startDate: '2025-01-15',
    pilotStartDate: '2025-02-01',
    productionDate: '2025-04-01',
    budgetYear1: 2_000_000,
    budgetYear2: 1_500_000,
    feasibilityScore: score(5, 5, 4, 4, 3, 5, 'Senior Director', '2025-01-20',
      'Strong exec mandate; change mgmt scope reflects broad population trained'),
    strategicAlignmentScore: 5,
    timeToValueScore: 4,
    roiTargets: [],
    measuredOutcomes: [],
    risks: [
      risk('risk-e1-1', 'Field adoption of AI tools stalls if Academy completion rates drop below 70%',
        'high', 'medium', 'Mandatory completion tied to performance reviews; monthly cohort reporting',
        'Academy Lead', 'open'),
    ],
    milestones: [
      ms('ms-e1-1', 'Pilot cohort (200 AEs) completes Module 1', '2025-02-28', 'done', 'Academy Lead', '', '2025-02-25'),
      ms('ms-e1-2', 'Full Sales org (250 AEs) certified on Tier 1 tools', '2025-06-30', 'done', 'Academy Lead', '', '2025-06-15'),
      ms('ms-e1-3', 'Marketing and CS cohorts certified', '2025-09-30', 'done', 'Academy Lead', '', '2025-09-22'),
      ms('ms-e1-4', 'Advanced AI fluency track launched (Tier 2 tools)', '2026-03-31', 'done', 'Academy Lead', '', '2026-03-28'),
      ms('ms-e1-5', 'AI fluency score >3.8/5 across GTM org (pulse survey)', '2026-06-30', 'in_progress', 'Academy Lead'),
    ],
    notes: 'Current AI fluency score: 3.6/5.0 (Apr 2026 pulse). On track for June target.',
    tags: ['foundation', 'enablement', 'all-functions'],
    createdAt: '2025-01-15T08:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
  },

  // ── S1: Meeting Prep & Post-Call Summaries (Tier 1, Production) ──────────
  {
    id: 'agent-s1',
    code: 'S1',
    name: 'Meeting Prep & Post-Call Summaries',
    description: 'Ingests Salesforce account data and Gong call recordings to auto-generate pre-meeting briefings and post-call summaries with CRM-ready action items.',
    function: 'sales',
    type: 'agentic',
    tier: 'tier_1_quick_win',
    stage: 'production',
    buildBuyDecision: 'buy',
    vendor: 'Gong + internal prompt layer',
    owner: 'Sales AI Lead',
    ownerFunction: 'Sales',
    cdioPartner: 'Director, Sales Technology',
    startDate: '2025-06-01',
    pilotStartDate: '2025-08-01',
    productionDate: '2025-10-15',
    budgetYear1: 800_000,
    budgetYear2: 600_000,
    budgetYear3: 400_000,
    feasibilityScore: score(4, 5, 5, 4, 5, 5, 'Sales AI Lead', '2025-05-15',
      'Gong API well-documented; Salesforce integration mature; field reception very positive in pilot'),
    strategicAlignmentScore: 5,
    timeToValueScore: 5,
    roiTargets: [
      roiTarget('roi-s1-1', 'sga_efficiency',
        'Hours saved per AE per week (meeting prep + CRM notes)',
        'hours', 0, 2.5, '2026-03-31',
        'measured_value * hourly_rate * headcount * 52',
        { hourly_rate: 95, headcount: 250 },
        'Bi-weekly Qualtrics pulse survey (n≥80 AEs) + Gong session duration delta',
        true, '2025-07-20', 1.0,
        'Pre-deployment cohort (Sep 2025) vs post-deployment cohort (Oct–Nov 2025), controlled for deal size and AE tenure'),
    ],
    measuredOutcomes: [
      outcome('out-s1-1', 'roi-s1-1', '2025-11-15', 1.8, 2_223_000,
        'Qualtrics pulse survey (n=112)', 'Measurement Analyst',
        'Qualtrics export 2025-11-14', 'First post-launch measurement; adoption still ramping'),
      outcome('out-s1-2', 'roi-s1-1', '2026-02-14', 2.1, 2_593_500,
        'Qualtrics pulse survey (n=145) + Gong session delta', 'Measurement Analyst',
        'Qualtrics export 2026-02-13 / Gong API 2026-02-14',
        'Adoption at 83%. Gong delta corroborates survey (+1.9 hrs/AE/week)'),
      outcome('out-s1-3', 'roi-s1-1', '2026-05-01', 2.3, 2_840_500,
        'Qualtrics pulse survey (n=168)', 'Measurement Analyst',
        'Qualtrics export 2026-04-30',
        'Q1 FY26 measurement. Trajectory on track; 86% adoption of 250 AEs'),
    ],
    adoptionMetrics: s1Adoption(),
    risks: [
      risk('risk-s1-1', 'Gong contract renewal in Q4 2026 — pricing at risk if usage spikes',
        'medium', 'medium', 'Lock 3-year rate in current renewal negotiation', 'Sales AI Lead'),
      risk('risk-s1-2', 'AE survey fatigue may undercount hours saved over time',
        'low', 'high', 'Supplement with Gong session-length delta as objective proxy',
        'Measurement Analyst', 'mitigated'),
    ],
    milestones: [
      ms('ms-s1-1', 'Pilot launch: 50 AE cohort (Americas)', '2025-08-01', 'done', 'Sales AI Lead', '', '2025-08-01'),
      ms('ms-s1-2', 'Pilot readout and go/no-go decision', '2025-09-30', 'done', 'Sales AI Lead', '', '2025-09-25'),
      ms('ms-s1-3', 'Full AE population (250) live', '2025-12-01', 'done', 'Sales AI Lead', 'Achieved ahead of schedule', '2025-11-15'),
      ms('ms-s1-4', 'Reach 2.5 hrs/AE/week target', '2026-06-30', 'in_progress', 'Sales AI Lead'),
    ],
    notes: 'Latest measurement (May 2026): 2.3 hrs/AE/week. Kill threshold: 1.0 hr/week. On track.',
    tags: ['gong', 'salesforce', 'productivity', 'quick-win'],
    createdAt: '2025-06-01T08:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
  },

  // ── S2: AI CRM Auto-Update (Tier 1, Pilot) ───────────────────────────────
  {
    id: 'agent-s2',
    code: 'S2',
    name: 'AI CRM Auto-Update from Calls',
    description: 'Automatically updates Salesforce opportunity fields (stage, next steps, close date) from Gong call transcripts, eliminating manual CRM entry after each call.',
    function: 'sales',
    type: 'agentic',
    tier: 'tier_1_quick_win',
    stage: 'pilot',
    buildBuyDecision: 'buy',
    vendor: 'Gong + Salesforce Flow',
    owner: 'Sales AI Lead',
    ownerFunction: 'Sales',
    cdioPartner: 'Director, Sales Technology',
    startDate: '2025-10-01',
    pilotStartDate: '2026-02-01',
    budgetYear1: 600_000,
    budgetYear2: 450_000,
    feasibilityScore: score(4, 4, 5, 3, 4, 4, 'Sales AI Lead', '2025-09-15',
      'Gong→Salesforce write API well-tested; AE trust in auto-write is the adoption risk'),
    strategicAlignmentScore: 4,
    timeToValueScore: 5,
    roiTargets: [
      roiTarget('roi-s2-1', 'sga_efficiency',
        'Minutes saved per AE per day on CRM updates', 'hours',
        0, 0.5, '2026-09-30',
        'measured_value * hourly_rate * headcount * 260',
        { hourly_rate: 95, headcount: 250 },
        'CRM session time tracking (Salesforce admin report) + A/B pilot cohort comparison',
        false),
    ],
    measuredOutcomes: [],
    risks: [
      risk('risk-s2-1', 'AEs override auto-updates >30% of time, reducing ROI and creating CRM data quality issues',
        'high', 'medium', 'Human-in-the-loop confirmation UX for first 90 days; auto-commit only after trust established',
        'Sales AI Lead'),
    ],
    milestones: [
      ms('ms-s2-1', 'Integration build complete (Gong webhook → Salesforce Flow)', '2026-01-15', 'done', 'Director, Sales Technology', '', '2026-01-10'),
      ms('ms-s2-2', 'Pilot launch: 30 AE cohort (Americas Enterprise)', '2026-02-01', 'done', 'Sales AI Lead', '', '2026-02-01'),
      ms('ms-s2-3', 'Pilot readout: override rate, data quality, AE satisfaction', '2026-04-30', 'done', 'Sales AI Lead', 'Override rate 22% — within acceptable range'),
      ms('ms-s2-4', 'CFO approval of ROI target methodology', '2026-05-31', 'not_started', 'Measurement Analyst'),
      ms('ms-s2-5', 'Full AE rollout (250)', '2026-08-01', 'not_started', 'Sales AI Lead'),
    ],
    notes: 'Pilot override rate 22% (target <25%). AE satisfaction: 3.8/5. CFO methodology review pending.',
    tags: ['gong', 'salesforce', 'crm', 'automation'],
    createdAt: '2025-10-01T08:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
  },

  // ── S3: Account Intelligence Agent (Tier 1, Scale) ───────────────────────
  {
    id: 'agent-s3',
    code: 'S3',
    name: 'Account Intelligence Agent',
    description: 'Synthesizes 10-K filings, earnings calls, news, and internal Salesforce activity into an always-fresh account brief, surfacing whitespace and risk signals for AEs.',
    function: 'sales',
    type: 'predictive',
    tier: 'tier_1_quick_win',
    stage: 'scale',
    buildBuyDecision: 'build',
    owner: 'Sales AI Lead',
    ownerFunction: 'Sales',
    cdioPartner: 'Director, Data Engineering',
    startDate: '2025-08-01',
    pilotStartDate: '2026-01-15',
    productionDate: undefined,
    budgetYear1: 900_000,
    budgetYear2: 700_000,
    feasibilityScore: score(4, 4, 4, 4, 4, 4, 'Sales AI Lead', '2025-07-20',
      'Public data ingestion pipeline reliable; internal Salesforce join adds complexity'),
    strategicAlignmentScore: 4,
    timeToValueScore: 4,
    roiTargets: [
      roiTarget('roi-s3-1', 'revenue_acceleration',
        'Incremental pipeline from whitespace alerts acted upon ($)',
        'usd', 0, 8_000_000, '2026-12-31',
        'measured_value',
        {},
        'Salesforce opportunity tagging: origin = "AI Account Intelligence" + 90-day attribution window',
        false),
    ],
    measuredOutcomes: [],
    risks: [
      risk('risk-s3-1', 'Data freshness — public filings lag actual events by weeks',
        'medium', 'high', 'Supplement with real-time news API and earnings call transcript webhooks',
        'Director, Data Engineering'),
    ],
    milestones: [
      ms('ms-s3-1', 'Pilot launch: 40 AE cohort covering top 100 accounts', '2026-01-15', 'done', 'Sales AI Lead', '', '2026-01-15'),
      ms('ms-s3-2', 'Expand to full AE population (250)', '2026-04-30', 'done', 'Sales AI Lead', '', '2026-04-22'),
      ms('ms-s3-3', 'CFO ROI methodology approved', '2026-06-30', 'not_started', 'Measurement Analyst'),
      ms('ms-s3-4', 'First pipeline attribution measurement', '2026-09-30', 'not_started', 'Measurement Analyst'),
    ],
    notes: 'All 250 AEs now have access. Adoption at 68%. Working with Measurement Analyst on attribution tagging standard.',
    tags: ['account-intelligence', 'pipeline', 'research-automation'],
    createdAt: '2025-08-01T08:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
  },

  // ── M1: AI Content Generation (Tier 1, Pilot) ────────────────────────────
  {
    id: 'agent-m1',
    code: 'M1',
    name: 'AI Content Generation (Brand-Controlled)',
    description: 'Generates on-brand marketing copy, email sequences, and landing page variants from a governed prompt library, cutting content production time while preserving brand voice.',
    function: 'marketing',
    type: 'generative',
    tier: 'tier_1_quick_win',
    stage: 'pilot',
    buildBuyDecision: 'buy',
    vendor: 'Writer.ai',
    owner: 'Marketing AI Lead',
    ownerFunction: 'Marketing',
    cdioPartner: 'Director, Marketing Technology',
    startDate: '2025-09-01',
    pilotStartDate: '2026-02-15',
    budgetYear1: 700_000,
    budgetYear2: 550_000,
    feasibilityScore: score(5, 5, 5, 3, 4, 4, 'Marketing AI Lead', '2025-08-20',
      'Model maturity high; adoption risk is brand team comfort with AI-assisted copy'),
    strategicAlignmentScore: 4,
    timeToValueScore: 5,
    roiTargets: [
      roiTarget('roi-m1-1', 'sga_efficiency',
        'Hours saved per content marketer per week', 'hours',
        0, 6.0, '2026-12-31',
        'measured_value * hourly_rate * headcount * 52',
        { hourly_rate: 85, headcount: 25 },
        'Content team time-tracking tool (Toggl) pre vs post; monthly readout',
        false),
    ],
    measuredOutcomes: [],
    risks: [
      risk('risk-m1-1', 'Brand team rejects AI copy at >40% rate, negating time savings',
        'medium', 'medium', 'Structured brand voice training in Writer.ai; monthly quality audit with Brand team',
        'Marketing AI Lead'),
    ],
    milestones: [
      ms('ms-m1-1', 'Writer.ai brand kit configuration complete', '2026-01-31', 'done', 'Marketing AI Lead', '', '2026-01-28'),
      ms('ms-m1-2', 'Pilot launch: content team (25 people)', '2026-02-15', 'done', 'Marketing AI Lead', '', '2026-02-15'),
      ms('ms-m1-3', 'Pilot readout: acceptance rate, time savings, quality NPS', '2026-05-15', 'not_started', 'Marketing AI Lead'),
    ],
    notes: 'Pilot in progress. Early signals: 72% copy acceptance rate, ~4 hrs/week saved per writer. Formal measurement at 90 days.',
    tags: ['content', 'generative', 'brand', 'writer'],
    createdAt: '2025-09-01T08:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
  },

  // ── M2: Predictive Lead Scoring & Routing (Tier 1, Scale) ────────────────
  {
    id: 'agent-m2',
    code: 'M2',
    name: 'Predictive Lead Scoring & Routing',
    description: 'ML model scoring inbound leads on conversion probability using firmographic, behavioral, and intent signals; routes high-confidence leads directly to AE queues.',
    function: 'marketing',
    type: 'predictive',
    tier: 'tier_1_quick_win',
    stage: 'scale',
    buildBuyDecision: 'build',
    owner: 'Marketing AI Lead',
    ownerFunction: 'Marketing',
    cdioPartner: 'Director, Data Science',
    startDate: '2025-07-01',
    pilotStartDate: '2025-11-01',
    productionDate: undefined,
    budgetYear1: 900_000,
    budgetYear2: 700_000,
    feasibilityScore: score(4, 5, 4, 4, 4, 5, 'Marketing AI Lead', '2025-06-15',
      'Intent data from 6sense integrated; model training data strong from 3 years of CRM history'),
    strategicAlignmentScore: 5,
    timeToValueScore: 4,
    roiTargets: [
      roiTarget('roi-m2-1', 'revenue_acceleration',
        'Improvement in MQL-to-Opportunity conversion rate (percentage points)',
        'percentage', 2.8, 3.8, '2026-12-31',
        'measured_value * pipeline_value_per_point',
        { pipeline_value_per_point: 4_000_000 },
        'Salesforce funnel report: MQL source = "AI Scored" cohort vs control (unscored leads), 90-day attribution',
        false, undefined, 0.3,
        'AI-scored leads vs unscored leads matched on industry, company size, and source channel'),
    ],
    measuredOutcomes: [],
    risks: [
      risk('risk-m2-1', 'Model drift — lead mix shifts if demand gen channels change, degrading scoring accuracy',
        'medium', 'medium', 'Monthly model performance review; retrain quarterly with fresh labeled data',
        'Director, Data Science'),
    ],
    milestones: [
      ms('ms-m2-1', 'Model v1.0 trained and validated (AUC >0.82)', '2025-10-01', 'done', 'Director, Data Science', '', '2025-09-28'),
      ms('ms-m2-2', 'Pilot: AI scoring on 30% of inbound leads', '2025-11-01', 'done', 'Marketing AI Lead', '', '2025-11-01'),
      ms('ms-m2-3', 'Expand to 100% of inbound leads', '2026-02-01', 'done', 'Marketing AI Lead', '', '2026-01-27'),
      ms('ms-m2-4', 'CFO ROI methodology approval', '2026-06-30', 'not_started', 'Measurement Analyst'),
      ms('ms-m2-5', 'First 90-day conversion rate measurement', '2026-07-31', 'not_started', 'Measurement Analyst'),
    ],
    notes: 'All inbound leads scored since Feb 2026. Early signal: high-confidence leads (score ≥0.75) converting at 4.1% vs 2.6% control. Formal attribution window closes July.',
    tags: ['lead-scoring', 'ml-model', '6sense', 'pipeline'],
    createdAt: '2025-07-01T08:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
  },

  // ── C1: Tier-1 Support Deflection (Tier 1, Production) ───────────────────
  {
    id: 'agent-c1',
    code: 'C1',
    name: 'Tier-1 Support Deflection',
    description: 'Agentic AI handling routine customer inquiries (billing, provisioning status, FAQ) via natural language, deflecting tickets before they reach the CS team queue.',
    function: 'customer_success',
    type: 'agentic',
    tier: 'tier_1_quick_win',
    stage: 'production',
    buildBuyDecision: 'buy',
    vendor: 'Zendesk AI + custom escalation logic',
    owner: 'CS AI Lead',
    ownerFunction: 'Customer Success',
    cdioPartner: 'Director, Customer Technology',
    startDate: '2025-07-01',
    pilotStartDate: '2025-09-15',
    productionDate: '2025-12-01',
    budgetYear1: 1_200_000,
    budgetYear2: 900_000,
    budgetYear3: 750_000,
    feasibilityScore: score(4, 4, 4, 5, 4, 5, 'CS AI Lead', '2025-06-20',
      'Zendesk AI mature; knowledge base quality is key risk — currently 60% digitized'),
    strategicAlignmentScore: 5,
    timeToValueScore: 5,
    roiTargets: [
      roiTarget('roi-c1-1', 'capacity_creation',
        'Tier-1 ticket deflection rate (%)', 'percentage',
        0, 35, '2026-06-30',
        'measured_value / 100 * annual_ticket_volume * cost_per_ticket',
        { annual_ticket_volume: 50_000, cost_per_ticket: 85 },
        'Zendesk report: tickets closed by AI agent / total tickets (30-day rolling)',
        true, '2025-08-10', 15,
        'Pre-launch baseline (Oct 2025): 0% AI deflection; post-launch monthly cohorts'),
    ],
    measuredOutcomes: [
      outcome('out-c1-1', 'roi-c1-1', '2026-01-15', 28, 1_190_000,
        'Zendesk admin report (Dec 2025 full month)', 'CS AI Lead',
        'Zendesk export 2026-01-14',
        'First full month in production. Knowledge base at 60% coverage — gap driving missed deflections'),
      outcome('out-c1-2', 'roi-c1-1', '2026-04-10', 31, 1_317_500,
        'Zendesk admin report (Mar 2026 full month)', 'Measurement Analyst',
        'Zendesk export 2026-04-09',
        'KB coverage now 78%. Deflection improving. On track for 35% target by June.'),
    ],
    adoptionMetrics: c1Adoption(),
    risks: [
      risk('risk-c1-1', 'Knowledge base gaps (<100% digitized) cap deflection rate ceiling below 35% target',
        'high', 'high', 'KB digitization sprint: target 90% coverage by May 2026; tracked weekly',
        'Director, Customer Technology'),
      risk('risk-c1-2', 'Customer CSAT dips if AI fails to escalate edge cases correctly',
        'medium', 'low', 'Human escalation trigger tuning; CSAT monitored weekly on AI-handled tickets',
        'CS AI Lead', 'mitigated'),
    ],
    milestones: [
      ms('ms-c1-1', 'Pilot: 20% of inbound tickets routed to AI', '2025-09-15', 'done', 'CS AI Lead', '', '2025-09-15'),
      ms('ms-c1-2', 'Go/no-go: CSAT ≥3.8, deflection ≥20%', '2025-11-01', 'done', 'CS AI Lead', 'CSAT 3.9, deflection 24% — approved', '2025-10-30'),
      ms('ms-c1-3', 'Full production: all inbound tickets routed', '2025-12-01', 'done', 'CS AI Lead', '', '2025-12-01'),
      ms('ms-c1-4', 'Knowledge base coverage ≥90%', '2026-05-31', 'in_progress', 'Director, Customer Technology'),
      ms('ms-c1-5', 'Reach 35% deflection rate target', '2026-06-30', 'in_progress', 'CS AI Lead'),
    ],
    notes: 'KB coverage: 78% (target 90% by May). Deflection: 31%. CSAT on AI-handled tickets: 3.7 (slight dip — investigating edge case gaps).',
    tags: ['zendesk', 'deflection', 'automation', 'csat'],
    createdAt: '2025-07-01T08:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
  },

  // ── C2: Predictive Customer Health Score (Tier 1, Pilot) ─────────────────
  {
    id: 'agent-c2',
    code: 'C2',
    name: 'Predictive Customer Health Score',
    description: 'ML model combining product usage, support ticket sentiment, contract renewal proximity, and executive engagement to produce a 0–100 health score for each account.',
    function: 'customer_success',
    type: 'predictive',
    tier: 'tier_1_quick_win',
    stage: 'pilot',
    buildBuyDecision: 'build',
    owner: 'CS AI Lead',
    ownerFunction: 'Customer Success',
    cdioPartner: 'Director, Data Science',
    startDate: '2025-09-01',
    pilotStartDate: '2026-03-01',
    budgetYear1: 800_000,
    budgetYear2: 600_000,
    feasibilityScore: score(3, 4, 4, 4, 4, 4, 'CS AI Lead', '2025-08-15',
      'Product telemetry data partially available; need data engineering work to unify signals'),
    strategicAlignmentScore: 5,
    timeToValueScore: 4,
    roiTargets: [
      roiTarget('roi-c2-1', 'revenue_acceleration',
        'Churn reduction: accounts flagged red (health <40) and saved ($ARR)',
        'usd', 0, 5_000_000, '2026-12-31',
        'measured_value',
        {},
        'Salesforce: renewals where health score triggered CSM intervention and account renewed (at-risk tag applied)',
        false, undefined, 500_000),
    ],
    measuredOutcomes: [],
    risks: [
      risk('risk-c2-1', 'Product telemetry data missing for 30% of install base — scores unreliable for those accounts',
        'high', 'high', 'Data engineering sprint to connect telemetry pipeline; timeline Q2 2026',
        'Director, Data Science'),
    ],
    milestones: [
      ms('ms-c2-1', 'Product telemetry pipeline unified (100% of install base)', '2026-02-28', 'missed', 'Director, Data Science', 'Slipped — now targeting May 2026'),
      ms('ms-c2-2', 'Model v1.0 trained (AUC >0.80 on churn prediction)', '2026-04-30', 'done', 'Director, Data Science', '', '2026-04-25'),
      ms('ms-c2-3', 'Pilot: scores live for 50 top accounts', '2026-03-01', 'done', 'CS AI Lead', '', '2026-03-01'),
      ms('ms-c2-4', 'Telemetry gap closed (100% coverage)', '2026-05-31', 'in_progress', 'Director, Data Science'),
      ms('ms-c2-5', 'Roll out to full install base; CFO methodology approval', '2026-07-31', 'not_started', 'CS AI Lead'),
    ],
    notes: 'Pilot running on top 50 accounts. Telemetry gap (30%) is the critical blocker — data engineering sprint underway.',
    tags: ['health-score', 'churn-prevention', 'ml-model'],
    createdAt: '2025-09-01T08:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
  },

  // ── C3: AI-Augmented QBR Prep (Tier 1, Design) ───────────────────────────
  {
    id: 'agent-c3',
    code: 'C3',
    name: 'AI-Augmented QBR Prep',
    description: 'Generates a structured QBR deck skeleton from Salesforce usage data, health score trends, open cases, and renewal context — CSMs edit and present; AI does the assembly.',
    function: 'customer_success',
    type: 'predictive',
    tier: 'tier_1_quick_win',
    stage: 'design',
    buildBuyDecision: 'build',
    owner: 'CS AI Lead',
    ownerFunction: 'Customer Success',
    cdioPartner: 'Director, Customer Technology',
    startDate: '2026-01-01',
    budgetYear1: 500_000,
    budgetYear2: 350_000,
    feasibilityScore: score(3, 4, 5, 4, 3, 4, 'CS AI Lead', '2026-01-15',
      'Deck generation straightforward once data sources unified; depends on C2 health score being live'),
    strategicAlignmentScore: 4,
    timeToValueScore: 4,
    roiTargets: [
      roiTarget('roi-c3-1', 'sga_efficiency',
        'Hours saved per CSM per QBR cycle', 'hours',
        0, 4.0, '2026-12-31',
        'measured_value * hourly_rate * headcount * qbr_cycles_per_year',
        { hourly_rate: 90, headcount: 80, qbr_cycles_per_year: 4 },
        'CSM time log (Toggl) pre vs post for QBR prep; 2-quarter comparison',
        false),
    ],
    measuredOutcomes: [],
    risks: [
      risk('risk-c3-1', 'Dependency on C2 health score data — if C2 delayed, C3 deck quality suffers',
        'medium', 'high', 'Design C3 to degrade gracefully — generate deck with placeholder health section until C2 live',
        'CS AI Lead'),
    ],
    milestones: [
      ms('ms-c3-1', 'Design spec completed and signed off by CS leadership', '2026-04-30', 'done', 'CS AI Lead', '', '2026-04-28'),
      ms('ms-c3-2', 'Engineering build complete (v1 deck generator)', '2026-07-15', 'not_started', 'Director, Customer Technology'),
      ms('ms-c3-3', 'Pilot with 10 CSMs on Q3 QBR cycle', '2026-08-01', 'not_started', 'CS AI Lead'),
    ],
    notes: 'Design complete. Blocked on C2 telemetry gap — coordinating dependency with data engineering team.',
    tags: ['qbr', 'deck-generation', 'csm-productivity'],
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
  },

  // ── S4: Personalized Outbound at Scale (Tier 2, Design) ──────────────────
  {
    id: 'agent-s4',
    code: 'S4',
    name: 'Personalized Outbound at Scale',
    description: 'Agentic system generating personalized outbound sequences for each prospect using company news, LinkedIn signals, and ICP-fit scoring — 10x SDR throughput.',
    function: 'sales',
    type: 'agentic',
    tier: 'tier_2_strategic_bet',
    stage: 'design',
    buildBuyDecision: 'hybrid',
    vendor: 'Outreach + Clay + internal LLM layer',
    owner: 'Sales AI Lead',
    ownerFunction: 'Sales',
    cdioPartner: 'Director, Sales Technology',
    startDate: '2026-02-01',
    budgetYear1: 1_200_000,
    budgetYear2: 950_000,
    feasibilityScore: score(3, 4, 3, 3, 3, 3, 'Sales AI Lead', '2026-01-25',
      'Personalization quality dependent on signal quality; SDR change management is the hardest part'),
    strategicAlignmentScore: 5,
    timeToValueScore: 3,
    roiTargets: [
      roiTarget('roi-s4-1', 'revenue_acceleration',
        'Incremental pipeline generated by AI-personalized outbound ($)',
        'usd', 0, 15_000_000, '2026-12-31',
        'measured_value',
        {},
        'Outreach sequence tagging: origin = "AI Personalized" + Salesforce opportunity attribution (90-day window)',
        false),
    ],
    measuredOutcomes: [],
    risks: [
      risk('risk-s4-1', 'Generic AI copy degrades reply rates — worse than human SDR baseline',
        'high', 'medium', 'A/B test human vs AI sequences; kill if AI reply rate <80% of human baseline',
        'Sales AI Lead'),
      risk('risk-s4-2', 'Data privacy: LinkedIn scraping compliance risk',
        'medium', 'low', 'Use only Clay-licensed data sources; legal review before launch',
        'Legal / Compliance'),
    ],
    milestones: [
      ms('ms-s4-1', 'Vendor selection complete (Clay vs ZoomInfo enrichment)', '2026-05-31', 'not_started', 'Sales AI Lead'),
      ms('ms-s4-2', 'Design spec and A/B testing methodology approved', '2026-06-30', 'not_started', 'Sales AI Lead'),
      ms('ms-s4-3', 'Pilot: 5 SDRs, 200 prospects (Americas)', '2026-09-01', 'not_started', 'Sales AI Lead'),
    ],
    notes: 'In design. Vendor evaluation underway (Clay vs ZoomInfo enrichment layer).',
    tags: ['outbound', 'sdr', 'clay', 'outreach', 'personalization'],
    createdAt: '2026-02-01T08:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
  },

  // ── S5: Real-Time Deal Coaching (Tier 2, Design) ─────────────────────────
  {
    id: 'agent-s5',
    code: 'S5',
    name: 'Real-Time Deal Coaching',
    description: 'Analyzes deal health from Salesforce activity, Gong call patterns, and competitive intel to surface next-best-action recommendations and flag at-risk deals to managers.',
    function: 'sales',
    type: 'predictive',
    tier: 'tier_2_strategic_bet',
    stage: 'design',
    buildBuyDecision: 'buy',
    vendor: 'Clari or Gong Forecast',
    owner: 'Sales AI Lead',
    ownerFunction: 'Sales',
    cdioPartner: 'Director, Sales Technology',
    startDate: '2026-03-01',
    budgetYear1: 1_100_000,
    budgetYear2: 900_000,
    feasibilityScore: score(4, 3, 3, 3, 3, 4, 'Sales AI Lead', '2026-02-15',
      'Deal data in Salesforce is good; model maturity depends on vendor selection'),
    strategicAlignmentScore: 5,
    timeToValueScore: 3,
    roiTargets: [
      roiTarget('roi-s5-1', 'revenue_acceleration',
        'Win rate improvement on AI-coached deals (percentage points)',
        'percentage', 0, 3.0, '2026-12-31',
        'measured_value * total_pipeline * 0.01',
        { total_pipeline: 500_000_000 },
        'Salesforce opportunity win rate: AI-coached cohort vs matched uncoached control; 6-month trailing',
        false),
    ],
    measuredOutcomes: [],
    risks: [
      risk('risk-s5-1', 'Sales managers resist AI coaching overlay — perceived as surveillance',
        'high', 'medium', 'Frame as "deal acceleration" not monitoring; manager champions recruited first',
        'Field Coach'),
    ],
    milestones: [
      ms('ms-s5-1', 'Vendor bake-off: Clari vs Gong Forecast (30-day POC)', '2026-06-30', 'not_started', 'Sales AI Lead'),
      ms('ms-s5-2', 'Design spec approved by Sales VP', '2026-07-31', 'not_started', 'Sales AI Lead'),
    ],
    notes: 'Awaiting vendor bake-off (planned Q2). Clari and Gong Forecast both shortlisted.',
    tags: ['deal-coaching', 'forecasting', 'clari', 'win-rate'],
    createdAt: '2026-03-01T08:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
  },

  // ── S6: AI-Augmented Forecasting (Tier 2, Pilot) ─────────────────────────
  {
    id: 'agent-s6',
    code: 'S6',
    name: 'AI-Augmented Forecasting',
    description: 'ML model producing an independent forecast signal alongside the rep-submitted forecast, flagging deals where AI confidence diverges significantly from rep call.',
    function: 'sales',
    type: 'predictive',
    tier: 'tier_2_strategic_bet',
    stage: 'pilot',
    buildBuyDecision: 'build',
    owner: 'Sales AI Lead',
    ownerFunction: 'Sales',
    cdioPartner: 'Director, Data Science',
    startDate: '2025-11-01',
    pilotStartDate: '2026-03-01',
    budgetYear1: 800_000,
    budgetYear2: 650_000,
    feasibilityScore: score(4, 4, 4, 4, 3, 5, 'Sales AI Lead', '2025-10-20',
      'Historical CRM data strong; change mgmt: CFO and Sales VP must trust AI signal over rep call'),
    strategicAlignmentScore: 5,
    timeToValueScore: 3,
    roiTargets: [
      roiTarget('roi-s6-1', 'quality_uplift',
        'Forecast accuracy improvement (MAPE reduction in percentage points)',
        'percentage', 18, 8, '2026-12-31',
        'measured_value * 0.5 * annual_revenue',
        { annual_revenue: 2_000_000_000 },
        'Weekly MAPE comparison: AI model vs rep-submitted forecast vs actual closed; CFO finance team validates',
        false, undefined, undefined,
        'AI forecast vs rep forecast on same deal set; actual close used as ground truth'),
    ],
    measuredOutcomes: [],
    risks: [
      risk('risk-s6-1', 'Reps game the model by submitting conservative forecasts to beat AI',
        'medium', 'medium', 'Lock AI input features so reps cannot directly influence model inputs',
        'Director, Data Science'),
    ],
    milestones: [
      ms('ms-s6-1', 'Model v1.0 MAPE validation on FY25 historical data', '2026-01-31', 'done', 'Director, Data Science', '', '2026-01-28'),
      ms('ms-s6-2', 'Pilot: AI signal visible to Sales VP and 3 regional managers', '2026-03-01', 'done', 'Sales AI Lead', '', '2026-03-01'),
      ms('ms-s6-3', 'MAPE comparison readout (pilot quarter)', '2026-06-30', 'not_started', 'Measurement Analyst'),
      ms('ms-s6-4', 'CFO approval and full rollout', '2026-09-30', 'not_started', 'Sales AI Lead'),
    ],
    notes: 'Pilot live with Sales VP and 3 regional managers seeing AI signal. Q2 readout planned June 2026.',
    tags: ['forecasting', 'mape', 'ml-model', 'finance'],
    createdAt: '2025-11-01T08:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
  },

  // ── S7: Proposal & SOW Generation (Tier 2, Design) ───────────────────────
  {
    id: 'agent-s7',
    code: 'S7',
    name: 'Proposal & SOW Generation',
    description: 'Generates first-draft proposals and statements of work from deal parameters, approved product catalog, and past-winning-proposal library — cuts proposal cycle time by 60%.',
    function: 'sales',
    type: 'predictive',
    tier: 'tier_2_strategic_bet',
    stage: 'design',
    buildBuyDecision: 'build',
    owner: 'Sales AI Lead',
    ownerFunction: 'Sales',
    cdioPartner: 'Director, Sales Technology',
    startDate: '2026-03-01',
    budgetYear1: 900_000,
    budgetYear2: 700_000,
    feasibilityScore: score(3, 4, 3, 4, 3, 4, 'Sales AI Lead', '2026-02-20',
      'Past proposal library partially digitized; legal and deal desk approval workflow adds complexity'),
    strategicAlignmentScore: 4,
    timeToValueScore: 3,
    roiTargets: [
      roiTarget('roi-s7-1', 'sga_efficiency',
        'Reduction in proposal cycle time (days)', 'days',
        14, 6, '2026-12-31',
        'time_saved_days * deals_per_year * fully_loaded_deal_desk_day_rate',
        { time_saved_days: 8, deals_per_year: 500, fully_loaded_deal_desk_day_rate: 760 },
        'Salesforce opportunity: proposal sent date vs opportunity created date; compare AI-assisted vs manual cohorts',
        false),
    ],
    measuredOutcomes: [],
    risks: [
      risk('risk-s7-1', 'Legal rejects AI-generated SOW clauses — rework time offsets savings',
        'high', 'medium', 'Pre-approved clause library built with Legal before launch; AI selects from approved clauses only',
        'Legal / Deal Desk'),
    ],
    milestones: [
      ms('ms-s7-1', 'Past proposal library digitized and tagged (200 proposals)', '2026-06-30', 'not_started', 'Director, Sales Technology'),
      ms('ms-s7-2', 'Legal approves clause library v1.0', '2026-07-31', 'not_started', 'Legal / Deal Desk'),
      ms('ms-s7-3', 'Pilot: Deal Desk team (10 people)', '2026-09-01', 'not_started', 'Sales AI Lead'),
    ],
    notes: 'Design phase. Proposal library digitization is the critical path item (target Q2 2026).',
    tags: ['proposal', 'sow', 'deal-desk', 'legal'],
    createdAt: '2026-03-01T08:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
  },

  // ── S10: Territory & Account Optimization (Tier 2, Evaluation) ───────────
  {
    id: 'agent-s10',
    code: 'S10',
    name: 'Territory & Account Optimization',
    description: 'Algorithmic territory design and account segmentation model that rebalances AE workloads based on account potential, geographic density, and historical win rates.',
    function: 'sales',
    type: 'predictive',
    tier: 'tier_2_strategic_bet',
    stage: 'evaluation',
    buildBuyDecision: 'tbd',
    owner: 'Sales AI Lead',
    ownerFunction: 'Sales',
    cdioPartner: 'Director, Data Science',
    startDate: '2026-04-01',
    budgetYear1: 700_000,
    feasibilityScore: score(4, 3, 3, 3, 4, 3, 'Sales AI Lead', '2026-03-20',
      'Account data available; political viability moderate — territory changes affect AE comp'),
    strategicAlignmentScore: 4,
    timeToValueScore: 2,
    roiTargets: [
      roiTarget('roi-s10-1', 'revenue_acceleration',
        'Incremental revenue from optimized territory coverage ($)', 'usd',
        0, 10_000_000, '2027-06-30',
        'measured_value',
        {},
        'Year-over-year comparison of territory performance pre vs post rebalance (matched on market conditions)',
        false),
    ],
    measuredOutcomes: [],
    risks: [
      risk('risk-s10-1', 'Territory rebalancing triggers AE attrition if perceived as punitive',
        'critical', 'medium', 'Communicate as capacity expansion; ensure no AE quota reduces; HR involved in design',
        'CHRO / Sales VP'),
    ],
    milestones: [
      ms('ms-s10-1', 'Feasibility study and make vs buy decision', '2026-06-30', 'not_started', 'Sales AI Lead'),
      ms('ms-s10-2', 'Stakeholder alignment: Sales VP, HR, Finance', '2026-07-31', 'not_started', 'Senior Director'),
    ],
    notes: 'Early evaluation. High political sensitivity — needs CHRO and Sales VP co-sponsorship before proceeding.',
    tags: ['territory', 'segmentation', 'capacity-planning'],
    createdAt: '2026-04-01T08:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
  },

  // ── M3: ABM Personalization at Scale (Tier 2, Design) ────────────────────
  {
    id: 'agent-m3',
    code: 'M3',
    name: 'ABM Personalization at Scale',
    description: 'Agentic system delivering account-specific content, ad creative, and email sequences to 500+ named accounts simultaneously — human-curated strategy, AI-executed delivery.',
    function: 'marketing',
    type: 'agentic',
    tier: 'tier_2_strategic_bet',
    stage: 'design',
    buildBuyDecision: 'hybrid',
    vendor: 'Demandbase + internal orchestration',
    owner: 'Marketing AI Lead',
    ownerFunction: 'Marketing',
    cdioPartner: 'Director, Marketing Technology',
    startDate: '2026-02-01',
    budgetYear1: 1_100_000,
    budgetYear2: 900_000,
    feasibilityScore: score(3, 3, 3, 3, 3, 3, 'Marketing AI Lead', '2026-01-20',
      'Demandbase integration mature; orchestration layer complexity is high; content approval workflow needed'),
    strategicAlignmentScore: 5,
    timeToValueScore: 3,
    roiTargets: [
      roiTarget('roi-m3-1', 'revenue_acceleration',
        'Pipeline influenced by AI-personalized ABM ($)', 'usd',
        0, 20_000_000, '2026-12-31',
        'measured_value',
        {},
        'Demandbase influence reporting + Salesforce opportunity source tagging (90-day touch window)',
        false),
    ],
    measuredOutcomes: [],
    risks: [
      risk('risk-m3-1', 'AI content personalization at volume degrades brand quality perception',
        'medium', 'medium', 'All AI content requires Marketing approval before delivery; spot audit 10% monthly',
        'Marketing AI Lead'),
    ],
    milestones: [
      ms('ms-m3-1', 'Design spec and content governance framework approved', '2026-06-30', 'not_started', 'Marketing AI Lead'),
      ms('ms-m3-2', 'Pilot: 50 named accounts', '2026-09-01', 'not_started', 'Marketing AI Lead'),
    ],
    notes: 'Design in progress. Content governance framework is the critical design decision.',
    tags: ['abm', 'demandbase', 'personalization', 'enterprise'],
    createdAt: '2026-02-01T08:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
  },

  // ── M4: Campaign Optimization Agent (Tier 2, Evaluation) ─────────────────
  {
    id: 'agent-m4',
    code: 'M4',
    name: 'Campaign Optimization Agent',
    description: 'Autonomous agent that adjusts bid strategies, creative rotation, and audience targeting across paid channels in real time based on performance signals.',
    function: 'marketing',
    type: 'agentic',
    tier: 'tier_2_strategic_bet',
    stage: 'evaluation',
    buildBuyDecision: 'buy',
    vendor: 'Metadata.io or Albert AI',
    owner: 'Marketing AI Lead',
    ownerFunction: 'Marketing',
    cdioPartner: 'Director, Marketing Technology',
    startDate: '2026-04-01',
    budgetYear1: 850_000,
    feasibilityScore: score(4, 4, 3, 3, 3, 3, 'Marketing AI Lead', '2026-03-15',
      'Vendor solutions mature; autonomous bidding requires strong budget controls and human guardrails'),
    strategicAlignmentScore: 4,
    timeToValueScore: 3,
    roiTargets: [
      roiTarget('roi-m4-1', 'revenue_acceleration',
        'Improvement in cost-per-MQL from paid channels (%)', 'percentage',
        0, 20, '2026-12-31',
        'measured_value / 100 * total_paid_spend',
        { total_paid_spend: 8_000_000 },
        'Platform reporting (Google/LinkedIn) + Salesforce MQL source tracking; 90-day rolling average',
        false),
    ],
    measuredOutcomes: [],
    risks: [
      risk('risk-m4-1', 'Autonomous bidding causes budget overrun without proper guardrails',
        'high', 'low', 'Hard budget caps in platform; daily spend alerts; human approval required for >$10K daily changes',
        'Marketing AI Lead'),
    ],
    milestones: [
      ms('ms-m4-1', 'Vendor evaluation complete (Metadata vs Albert)', '2026-06-30', 'not_started', 'Marketing AI Lead'),
      ms('ms-m4-2', 'CFO approval of budget control framework', '2026-07-31', 'not_started', 'Measurement Analyst'),
    ],
    notes: 'Evaluation phase. Vendor bake-off planned Q2.',
    tags: ['paid-media', 'campaign', 'autonomous', 'bidding'],
    createdAt: '2026-04-01T08:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
  },

  // ── C4: Proactive Intervention Agent (Tier 2, Design) ────────────────────
  {
    id: 'agent-c4',
    code: 'C4',
    name: 'Proactive Intervention Agent',
    description: 'Monitors health score degradation signals and automatically triggers CSM outreach, escalation, or success play sequences before customers self-report issues.',
    function: 'customer_success',
    type: 'agentic',
    tier: 'tier_2_strategic_bet',
    stage: 'design',
    buildBuyDecision: 'build',
    owner: 'CS AI Lead',
    ownerFunction: 'Customer Success',
    cdioPartner: 'Director, Customer Technology',
    startDate: '2026-03-01',
    budgetYear1: 900_000,
    budgetYear2: 700_000,
    feasibilityScore: score(3, 4, 3, 3, 4, 4, 'CS AI Lead', '2026-02-20',
      'Depends on C2 health score being reliable; intervention logic needs CSM co-design'),
    strategicAlignmentScore: 5,
    timeToValueScore: 3,
    roiTargets: [
      roiTarget('roi-c4-1', 'revenue_acceleration',
        'ARR retained via AI-triggered interventions ($)', 'usd',
        0, 8_000_000, '2027-06-30',
        'measured_value',
        {},
        'Salesforce: renewals where proactive intervention sequence fired and account renewed (at-risk reversal)',
        false),
    ],
    measuredOutcomes: [],
    risks: [
      risk('risk-c4-1', 'False positive interventions damage customer relationships if CSM outreach feels tone-deaf',
        'high', 'medium', 'CSM reviews all AI-triggered intervention drafts before sending; precision threshold >0.75',
        'CS AI Lead'),
    ],
    milestones: [
      ms('ms-c4-1', 'Design spec complete (trigger conditions, intervention playbooks)', '2026-07-31', 'not_started', 'CS AI Lead'),
      ms('ms-c4-2', 'Pilot with 5 CSMs on 30 accounts', '2026-10-01', 'not_started', 'CS AI Lead'),
    ],
    notes: 'Design in progress. Blocked on C2 health score stability — will not proceed until C2 telemetry gap closed.',
    tags: ['proactive', 'churn-prevention', 'playbooks', 'automation'],
    createdAt: '2026-03-01T08:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
  },

  // ── C5: Expansion Opportunity Routing (Tier 2, Evaluation) ───────────────
  {
    id: 'agent-c5',
    code: 'C5',
    name: 'Expansion Opportunity Routing',
    description: 'Predictive model identifying upsell and cross-sell opportunities within existing accounts based on product usage patterns, contract utilization, and industry benchmarks.',
    function: 'customer_success',
    type: 'predictive',
    tier: 'tier_2_strategic_bet',
    stage: 'evaluation',
    buildBuyDecision: 'build',
    owner: 'CS AI Lead',
    ownerFunction: 'Customer Success',
    cdioPartner: 'Director, Data Science',
    startDate: '2026-04-01',
    budgetYear1: 750_000,
    feasibilityScore: score(4, 3, 4, 3, 3, 4, 'CS AI Lead', '2026-03-25',
      'Product usage data becoming available via C2 pipeline; expansion signal model similar to churn model'),
    strategicAlignmentScore: 4,
    timeToValueScore: 3,
    roiTargets: [
      roiTarget('roi-c5-1', 'revenue_acceleration',
        'Incremental NRR from AI-identified expansion opportunities ($)', 'usd',
        0, 12_000_000, '2027-06-30',
        'measured_value',
        {},
        'Salesforce expansion opportunities where source = "AI Expansion Routing"; 6-month close attribution',
        false),
    ],
    measuredOutcomes: [],
    risks: [
      risk('risk-c5-1', 'Model confuses high-usage (satisfied) with low-usage (at-risk) signals for expansion readiness',
        'medium', 'medium', 'Segment model by health score band; only surface expansion to green/amber accounts',
        'Director, Data Science'),
    ],
    milestones: [
      ms('ms-c5-1', 'Feasibility assessment complete (data availability confirmed)', '2026-06-30', 'not_started', 'Director, Data Science'),
      ms('ms-c5-2', 'Model design approved; pilot scope defined', '2026-08-31', 'not_started', 'CS AI Lead'),
    ],
    notes: 'Early evaluation. Depends on C2 telemetry pipeline completing. Positive signal from Data Science team.',
    tags: ['expansion', 'nrr', 'upsell', 'cross-sell'],
    createdAt: '2026-04-01T08:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
  },

  // ── S8: AI Deal Desk (Tier 3, Evaluation) ────────────────────────────────
  {
    id: 'agent-s8',
    code: 'S8',
    name: 'AI Deal Desk',
    description: 'Agentic deal desk that auto-approves standard discount requests, generates deal-specific pricing recommendations, and routes non-standard deals to humans with a pre-built analysis package.',
    function: 'sales',
    type: 'agentic',
    tier: 'tier_3_flagship',
    stage: 'evaluation',
    buildBuyDecision: 'tbd',
    owner: 'Sales AI Lead',
    ownerFunction: 'Sales',
    cdioPartner: 'Director, Sales Technology',
    startDate: '2026-04-01',
    budgetYear1: 1_500_000,
    budgetYear2: 1_200_000,
    feasibilityScore: score(3, 3, 2, 3, 2, 3, 'Sales AI Lead', '2026-03-30',
      'Complex pricing logic and approval workflow integration; requires Finance and Legal co-design'),
    strategicAlignmentScore: 5,
    timeToValueScore: 2,
    roiTargets: [
      roiTarget('roi-s8-1', 'sga_efficiency',
        'Deal desk cycle time reduction (days per deal)', 'days',
        5, 1, '2027-06-30',
        'time_saved_days * deals_per_year * blended_deal_desk_day_rate',
        { time_saved_days: 4, deals_per_year: 2000, blended_deal_desk_day_rate: 580 },
        'Salesforce: deal desk ticket created date vs approval date; AI vs human cohort comparison',
        false),
      roiTarget('roi-s8-2', 'revenue_acceleration',
        'Deal velocity improvement — days to close reduction (days)', 'days',
        42, 35, '2027-06-30',
        'time_saved_days * closed_won_deals_per_year * average_deal_value * daily_time_value_rate',
        { time_saved_days: 7, closed_won_deals_per_year: 800, average_deal_value: 180_000, daily_time_value_rate: 0.0005 },
        'Salesforce: opportunity created date to close date; AI deal desk cohort vs manual cohort',
        false),
    ],
    measuredOutcomes: [],
    risks: [
      risk('risk-s8-1', 'AI pricing errors expose company to margin compression at scale',
        'critical', 'low', 'Hard floor rules coded in advance; Finance sign-off required on all pricing boundaries; weekly audit',
        'CFO / Finance'),
      risk('risk-s8-2', 'Deal desk team resists automation — job security concerns',
        'high', 'medium', 'Frame as capacity expansion enabling deal desk to focus on complex, high-value structuring',
        'CHRO / Sales VP'),
    ],
    milestones: [
      ms('ms-s8-1', 'Feasibility assessment: pricing system API access and integration complexity', '2026-06-30', 'not_started', 'Director, Sales Technology'),
      ms('ms-s8-2', 'Finance and Legal co-design workshop', '2026-07-31', 'not_started', 'Senior Director'),
    ],
    notes: 'Evaluation. Highest-complexity agent in portfolio. Requires CFO, Legal, and Finance co-sponsorship before proceeding.',
    tags: ['deal-desk', 'pricing', 'approval-workflow', 'agentic'],
    createdAt: '2026-04-01T08:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
  },

  // ── S9: Agentic Tier-1 Account Team Augmentation (Tier 3, Idea) ──────────
  {
    id: 'agent-s9',
    code: 'S9',
    name: 'Agentic Tier-1 Account Team Augmentation',
    description: 'AI agent functioning as a virtual team member for Tier-1 accounts — handling research, scheduling coordination, executive briefing prep, and relationship mapping at enterprise depth.',
    function: 'sales',
    type: 'agentic',
    tier: 'tier_3_flagship',
    stage: 'idea',
    buildBuyDecision: 'tbd',
    owner: 'Sales AI Lead',
    ownerFunction: 'Sales',
    startDate: '2026-05-01',
    budgetYear1: 2_000_000,
    budgetYear2: 1_800_000,
    feasibilityScore: score(2, 3, 2, 3, 2, 3, 'Sales AI Lead', '2026-04-20',
      'Requires multi-agent orchestration maturity not yet proven in enterprise contexts'),
    strategicAlignmentScore: 5,
    timeToValueScore: 1,
    roiTargets: [
      roiTarget('roi-s9-1', 'revenue_acceleration',
        'Incremental revenue from Tier-1 account expansion ($)', 'usd',
        0, 25_000_000, '2028-06-30',
        'measured_value',
        {},
        'Salesforce NRR and expansion ARR: Tier-1 accounts with AI augmentation vs matched control',
        false),
    ],
    measuredOutcomes: [],
    risks: [
      risk('risk-s9-1', 'Agentic orchestration at enterprise complexity not production-ready by planned timeline',
        'high', 'high', 'Gate on S11 Autonomous AIA proving out foundational orchestration patterns first',
        'Senior Director'),
    ],
    milestones: [
      ms('ms-s9-1', 'Concept validation with top 3 Tier-1 account teams', '2026-12-31', 'not_started', 'Sales AI Lead'),
    ],
    notes: 'Idea stage. Sequenced after S11 matures orchestration foundations.',
    tags: ['enterprise', 'tier-1', 'agentic', 'flagship'],
    createdAt: '2026-05-01T08:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
  },

  // ── S11: Autonomous Account Intelligence Agent (Tier 3, Idea) ────────────
  {
    id: 'agent-s11',
    code: 'S11',
    name: 'Autonomous Account Intelligence Agent',
    description: 'Fully autonomous agent continuously monitoring market events, relationship signals, and internal activity to proactively surface insights and recommended actions — no AE prompt required.',
    function: 'sales',
    type: 'agentic',
    tier: 'tier_3_flagship',
    stage: 'idea',
    buildBuyDecision: 'build',
    owner: 'Sales AI Lead',
    ownerFunction: 'Sales',
    cdioPartner: 'VP, AI Platform',
    startDate: '2026-06-01',
    budgetYear1: 2_500_000,
    budgetYear2: 2_000_000,
    feasibilityScore: score(2, 3, 2, 2, 2, 3, 'Sales AI Lead', '2026-04-25',
      'Foundation models approaching capability threshold; autonomous action in customer context requires extensive safeguarding'),
    strategicAlignmentScore: 5,
    timeToValueScore: 1,
    roiTargets: [
      roiTarget('roi-s11-1', 'revenue_acceleration',
        'Pipeline generated from autonomous insight actions ($)', 'usd',
        0, 30_000_000, '2028-12-31',
        'measured_value',
        {},
        'Salesforce: opportunities where AE action triggered by AI insight; 6-month attribution',
        false),
    ],
    measuredOutcomes: [],
    risks: [
      risk('risk-s11-1', 'Autonomous agent takes actions in customer-facing context without sufficient human oversight',
        'critical', 'medium', 'Human-in-the-loop for all external actions; internal research/synthesis only in v1',
        'CDIO / Legal'),
    ],
    milestones: [
      ms('ms-s11-1', 'Technical architecture review with VP AI Platform', '2026-09-30', 'not_started', 'Senior Director'),
    ],
    notes: 'Idea stage. Requires agentic orchestration infrastructure to mature (targeting 2027 build start).',
    tags: ['autonomous', 'flagship', 'agentic', '2027'],
    createdAt: '2026-05-01T08:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
  },

  // ── M6: AI-Native Marketing Operating Model (Tier 3, Idea) ───────────────
  {
    id: 'agent-m6',
    code: 'M6',
    name: 'AI-Native Marketing Operating Model',
    description: 'Full reimagination of the Marketing org around AI — human strategists directing networks of AI agents for demand gen, content, campaign execution, and measurement.',
    function: 'marketing',
    type: 'agentic',
    tier: 'tier_3_flagship',
    stage: 'idea',
    buildBuyDecision: 'tbd',
    owner: 'Marketing AI Lead',
    ownerFunction: 'Marketing',
    startDate: '2027-01-01',
    budgetYear1: 3_000_000,
    budgetYear2: 4_000_000,
    feasibilityScore: score(2, 3, 2, 2, 2, 3, 'Marketing AI Lead', '2026-04-10',
      'Requires M1–M4 all in production and proven; operating model change is the dominant risk'),
    strategicAlignmentScore: 5,
    timeToValueScore: 1,
    roiTargets: [
      roiTarget('roi-m6-1', 'capacity_creation',
        'Marketing headcount efficiency improvement (%)', 'percentage',
        0, 40, '2028-12-31',
        'measured_value / 100 * total_marketing_opex',
        { total_marketing_opex: 25_000_000 },
        'Marketing OpEx per unit of pipeline influenced; CFO annual review',
        false),
    ],
    measuredOutcomes: [],
    risks: [
      risk('risk-m6-1', 'Operating model transformation fails without strong CMO sponsorship and change management',
        'critical', 'medium', 'Sequence after M1–M4 all production; build CMO business case in 2026',
        'Senior Director / CMO'),
    ],
    milestones: [
      ms('ms-m6-1', 'Concept paper and CMO sponsorship secured', '2027-03-31', 'not_started', 'Marketing AI Lead'),
    ],
    notes: 'Long-horizon flagship. Intentionally sequenced after Tier 1 and Tier 2 Marketing agents are proven.',
    tags: ['operating-model', 'flagship', '2027', 'transformation'],
    createdAt: '2026-04-10T08:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
  },

  // ── C6: Predictive CS Operating Model (Tier 3, Idea) ─────────────────────
  {
    id: 'agent-c6',
    code: 'C6',
    name: 'Predictive Customer Success Operating Model',
    description: 'Reimagines the CS operating model around predictive AI — health scoring, intervention, QBR, and expansion all orchestrated by AI with human CSMs focused on strategic relationship work.',
    function: 'customer_success',
    type: 'agentic',
    tier: 'tier_3_flagship',
    stage: 'idea',
    buildBuyDecision: 'tbd',
    owner: 'CS AI Lead',
    ownerFunction: 'Customer Success',
    startDate: '2027-01-01',
    budgetYear1: 2_500_000,
    budgetYear2: 3_000_000,
    feasibilityScore: score(2, 3, 2, 2, 2, 3, 'CS AI Lead', '2026-04-15',
      'Requires C2, C3, C4, C5 all in production; org model change is primary risk'),
    strategicAlignmentScore: 5,
    timeToValueScore: 1,
    roiTargets: [
      roiTarget('roi-c6-1', 'capacity_creation',
        'CS capacity expansion (accounts per CSM improvement)', 'count',
        45, 75, '2028-12-31',
        'measured_value * csm_headcount * avg_arr_per_account',
        { csm_headcount: 80, avg_arr_per_account: 120_000 },
        'Salesforce accounts per active CSM; year-over-year comparison',
        false),
    ],
    measuredOutcomes: [],
    risks: [
      risk('risk-c6-1', 'CSM role redefinition creates attrition risk if not managed carefully',
        'critical', 'medium', 'Co-design operating model with CS team; position as career elevation not elimination',
        'CHRO / CS VP'),
    ],
    milestones: [
      ms('ms-c6-1', 'CS VP sponsorship and operating model concept paper', '2027-03-31', 'not_started', 'CS AI Lead'),
    ],
    notes: 'Long-horizon flagship. Sequenced after C2–C5 all in production.',
    tags: ['operating-model', 'flagship', '2027', 'csm'],
    createdAt: '2026-04-15T08:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
  },
];

// ─── Data Feasibility Assessments ────────────────────────────────────────────

export const SEED_DATA_FEASIBILITY: DataFeasibilityAssessment[] = [
  {
    agentId: 'agent-s1',
    cdioPartner: 'Director, Sales Technology',
    assessedAt: '2025-05-20',
    cdioSignedOff: true,
    cdioSignOffDate: '2025-06-01',
    overallReadiness: 5,
    gapSummary: 'No material data gaps. Gong API and Salesforce integration fully available and tested.',
    notes: 'Strong data foundation. Gong transcript quality excellent. Salesforce opportunity data complete for >95% of accounts.',
    requiredDataSources: [
      {
        id: 'ds-s1-1', sourceName: 'Gong Call Recordings & Transcripts',
        systemOwner: 'Director, Sales Technology', dataAvailability: 'available',
        dataQuality: 5, accessGranted: true, piiRisk: 'low',
      },
      {
        id: 'ds-s1-2', sourceName: 'Salesforce Opportunity & Account Data',
        systemOwner: 'Salesforce Admin', dataAvailability: 'available',
        dataQuality: 4, accessGranted: true, piiRisk: 'low',
        gapDescription: '~5% of accounts missing industry classification',
        closureAction: 'Enrichment run from ZoomInfo',
        closureOwner: 'Salesforce Admin',
        closureDate: '2025-07-15',
      },
    ],
  },
  {
    agentId: 'agent-c1',
    cdioPartner: 'Director, Customer Technology',
    assessedAt: '2025-06-25',
    cdioSignedOff: true,
    cdioSignOffDate: '2025-07-01',
    overallReadiness: 4,
    gapSummary: 'Knowledge base 60% digitized at assessment. Digitization sprint required to reach deflection target.',
    estimatedGapClosureDate: '2026-05-31',
    notes: 'Zendesk data access complete. KB gap is the primary constraint on deflection ceiling.',
    requiredDataSources: [
      {
        id: 'ds-c1-1', sourceName: 'Zendesk Ticket Data',
        systemOwner: 'Director, Customer Technology', dataAvailability: 'available',
        dataQuality: 4, accessGranted: true, piiRisk: 'low',
      },
      {
        id: 'ds-c1-2', sourceName: 'Customer Knowledge Base Articles',
        systemOwner: 'Director, Customer Technology', dataAvailability: 'partial',
        dataQuality: 3, accessGranted: true, piiRisk: 'none',
        gapDescription: 'Only 60% of KB articles digitized in structured format; 40% exist as PDFs or legacy HTML',
        closureAction: 'KB digitization sprint — convert all articles to structured markdown',
        closureOwner: 'Director, Customer Technology',
        closureDate: '2026-05-31',
      },
      {
        id: 'ds-c1-3', sourceName: 'Customer Contact & Account Database',
        systemOwner: 'Salesforce Admin', dataAvailability: 'available',
        dataQuality: 3, accessGranted: true, piiRisk: 'high',
        gapDescription: 'PII handling requires data masking before passing to AI layer',
        closureAction: 'Implement PII masking layer in Zendesk-AI connector',
        closureOwner: 'Director, Customer Technology',
        closureDate: '2025-09-01',
      },
    ],
  },
  {
    agentId: 'agent-m2',
    cdioPartner: 'Director, Data Science',
    assessedAt: '2025-06-20',
    cdioSignedOff: false,
    overallReadiness: 4,
    gapSummary: 'Training data strong (3 years of CRM history). 6sense intent data integrated. Minor gap: web behavioral signals incomplete for SMB segment.',
    notes: 'Data Science team has high confidence in training data quality. CDIO sign-off pending methodology review.',
    requiredDataSources: [
      {
        id: 'ds-m2-1', sourceName: 'Salesforce CRM (3yr Historical)',
        systemOwner: 'Salesforce Admin', dataAvailability: 'available',
        dataQuality: 4, accessGranted: true, piiRisk: 'low',
      },
      {
        id: 'ds-m2-2', sourceName: '6sense Intent Data',
        systemOwner: 'Director, Marketing Technology', dataAvailability: 'available',
        dataQuality: 4, accessGranted: true, piiRisk: 'none',
      },
      {
        id: 'ds-m2-3', sourceName: 'Web Behavioral Signals (GA4)',
        systemOwner: 'Director, Marketing Technology', dataAvailability: 'partial',
        dataQuality: 3, accessGranted: true, piiRisk: 'low',
        gapDescription: 'SMB segment under-represented in web behavioral data; GA4 consent gaps in EMEA',
        closureAction: 'Server-side tagging for EMEA; SMB signal augmentation from 6sense',
        closureOwner: 'Director, Marketing Technology',
        closureDate: '2026-03-31',
      },
    ],
  },
];

// ─── ROI Methodologies ────────────────────────────────────────────────────────

export const SEED_ROI_METHODOLOGIES: ROIMethodology[] = [
  {
    id: 'meth-s1-1',
    agentId: 'agent-s1',
    roiTargetId: 'roi-s1-1',
    version: 2,
    baselineMeasurementApproach: 'Pre-deployment time baseline established via Qualtrics survey (Sep 2025, n=98 AEs). AEs self-reported time spent on meeting prep and post-call CRM notes per week. Average baseline: 0 hours saved (pre-tool). Gong session duration data collected as objective corroboration.',
    comparatorGroupDefinition: 'Pre-deployment cohort (Sep 2025) vs post-deployment cohort (Oct 2025 onward). Controlled for: (a) deal size (enterprise vs commercial), (b) AE tenure (>1yr vs <1yr), (c) region (Americas, EMEA, APAC). Random assignment not feasible — tool deployed to all AEs simultaneously. Difference-in-differences approach used where historical averages serve as counterfactual.',
    keyAssumptions: [
      'Fully loaded AE hourly rate: $95 (includes salary, benefits, equity, overhead — validated by Finance in Jul 2025)',
      'AE headcount in scope: 250 (full GTM Sales org)',
      'Hours saved measured via bi-weekly Qualtrics pulse survey supplemented by Gong session delta',
      'Annual projection assumes 52 working weeks and stable headcount',
      'No seasonal adjustment applied (Equinix deal cycles relatively consistent)',
    ],
    knownLimitations: [
      'Self-reported survey hours may overestimate savings by 10-20% (social desirability bias)',
      'Does not capture quality uplift from better-prepared AEs (meeting effectiveness, win rate) — conservative by design',
      'Gong session delta captures AI session time but not all prep time (e.g., email research)',
      'Headcount assumed constant; actual savings scale with attrition/hiring',
    ],
    calculationWalkthrough: 'Step 1: Collect bi-weekly Qualtrics survey (target n≥80 AEs). Calculate mean hours saved per AE per week. Step 2: Corroborate with Gong session time: [time in AI-assisted sessions] - [pre-deployment baseline session time]. Step 3: Apply formula: hours_saved × $95/hr × 250 AEs × 52 weeks = annualized SG&A impact. Step 4: Present to CFO with both survey and Gong delta; CFO validates methodology quarterly.',
    signOffChain: [
      { role: 'Sales AI Lead', name: 'Sales AI Lead', signedOffAt: '2025-07-18', notes: 'Methodology agreed by function owner' },
      { role: 'CFO', name: 'CFO', signedOffAt: '2025-07-20', notes: 'Approved. Hourly rate confirmed by Finance. Quarterly re-validation required.' },
    ],
    createdAt: '2025-07-10T00:00:00Z',
    updatedAt: '2025-11-01T00:00:00Z',
  },
  {
    id: 'meth-c1-1',
    agentId: 'agent-c1',
    roiTargetId: 'roi-c1-1',
    version: 1,
    baselineMeasurementApproach: 'Pre-launch baseline: 0% AI deflection (Oct 2025). Zendesk ticket volume baseline: 50,000 annual tickets (FY25 actuals, validated by Finance). Cost-per-ticket: $85 (fully loaded: CSM time + platform cost + management overhead — Finance validated Aug 2025).',
    comparatorGroupDefinition: 'Month-over-month deflection rate from Zendesk admin report. Tickets closed by AI agent (Zendesk "Resolved by Bot" tag) as numerator; total inbound tickets as denominator. No A/B control — all tickets routed to AI layer post-launch.',
    keyAssumptions: [
      'Annual ticket volume: 50,000 (based on FY25 actuals; assumed flat for projection)',
      'Cost per ticket: $85 fully loaded (Finance-validated Aug 2025)',
      'Deflection = ticket closed by AI without human CSM involvement',
      'CSAT floor: must maintain ≥3.7 on AI-handled tickets to continue at current deflection rate',
    ],
    knownLimitations: [
      'Ticket volume may grow as Equinix expands — deflection rate held constant underestimates total savings if volume grows',
      'Does not capture CSM time freed for higher-value work (conservative)',
      'Zendesk "Resolved by Bot" tag requires manual audit quarterly to catch misclassifications',
    ],
    calculationWalkthrough: 'Step 1: Pull Zendesk monthly report: [tickets resolved by bot] / [total inbound tickets] = deflection %. Step 2: Apply formula: deflection_pct/100 × 50,000 annual tickets × $85/ticket = annual capacity created. Step 3: Annualize from monthly measurement. Step 4: CS AI Lead and Measurement Analyst sign off monthly; CFO reviews quarterly.',
    signOffChain: [
      { role: 'CS AI Lead', name: 'CS AI Lead', signedOffAt: '2025-08-05', notes: 'Methodology agreed; CSAT floor added as kill signal' },
      { role: 'CFO', name: 'CFO', signedOffAt: '2025-08-10', notes: 'Approved. Cost-per-ticket validated by Finance. Kill threshold: <15% deflection by Dec 2025.' },
    ],
    createdAt: '2025-08-01T00:00:00Z',
    updatedAt: '2025-08-10T00:00:00Z',
  },
];

// ─── ROI Audit Entries ────────────────────────────────────────────────────────

export const SEED_ROI_AUDIT_ENTRIES: ROIAuditEntry[] = [
  {
    id: 'audit-s1-1',
    agentId: 'agent-s1',
    roiTargetId: 'roi-s1-1',
    methodologyId: 'meth-s1-1',
    changedAt: '2025-07-10T14:00:00Z',
    changedBy: 'Sales AI Lead',
    changeType: 'target_created',
    newValue: JSON.stringify({ targetValue: 2.5, targetDate: '2026-03-31' }),
    rationale: 'Initial ROI target set based on pilot survey design and AE population sizing',
  },
  {
    id: 'audit-s1-2',
    agentId: 'agent-s1',
    roiTargetId: 'roi-s1-1',
    methodologyId: 'meth-s1-1',
    changedAt: '2025-07-20T10:00:00Z',
    changedBy: 'CFO',
    changeType: 'cfo_approved',
    rationale: 'CFO approved ROI target and methodology. Hourly rate confirmed at $95 by Finance team.',
  },
  {
    id: 'audit-s1-3',
    agentId: 'agent-s1',
    roiTargetId: 'roi-s1-1',
    measuredOutcomeId: 'out-s1-1',
    changedAt: '2025-11-15T16:00:00Z',
    changedBy: 'Measurement Analyst',
    changeType: 'outcome_recorded',
    newValue: JSON.stringify({ measuredValue: 1.8, monetizedValue: 2_223_000 }),
    rationale: 'First post-launch measurement. Adoption still ramping — 48% of AEs active.',
  },
  {
    id: 'audit-s1-4',
    agentId: 'agent-s1',
    roiTargetId: 'roi-s1-1',
    measuredOutcomeId: 'out-s1-2',
    changedAt: '2026-02-14T16:00:00Z',
    changedBy: 'Measurement Analyst',
    changeType: 'outcome_recorded',
    newValue: JSON.stringify({ measuredValue: 2.1, monetizedValue: 2_593_500 }),
    rationale: 'Q4 FY25 measurement. Gong delta (1.9 hrs) corroborates survey (2.1 hrs). Trajectory on track.',
  },
  {
    id: 'audit-s1-5',
    agentId: 'agent-s1',
    roiTargetId: 'roi-s1-1',
    measuredOutcomeId: 'out-s1-3',
    changedAt: '2026-05-01T16:00:00Z',
    changedBy: 'Measurement Analyst',
    changeType: 'outcome_recorded',
    newValue: JSON.stringify({ measuredValue: 2.3, monetizedValue: 2_840_500 }),
    rationale: 'Q1 FY26 measurement. 86% AE adoption. Trajectory within range for 2.5 target by June 2026.',
  },
  {
    id: 'audit-c1-1',
    agentId: 'agent-c1',
    roiTargetId: 'roi-c1-1',
    methodologyId: 'meth-c1-1',
    changedAt: '2025-08-05T09:00:00Z',
    changedBy: 'CS AI Lead',
    changeType: 'target_created',
    newValue: JSON.stringify({ targetValue: 35, targetDate: '2026-06-30', killThreshold: 15 }),
    rationale: 'Initial ROI target set; kill threshold of 15% set to protect against low-deflection scenario',
  },
  {
    id: 'audit-c1-2',
    agentId: 'agent-c1',
    roiTargetId: 'roi-c1-1',
    methodologyId: 'meth-c1-1',
    changedAt: '2025-08-10T11:00:00Z',
    changedBy: 'CFO',
    changeType: 'cfo_approved',
    rationale: 'CFO approved. Cost-per-ticket $85 confirmed by Finance. Kill threshold: <15% by Dec 2025.',
  },
  {
    id: 'audit-c1-3',
    agentId: 'agent-c1',
    roiTargetId: 'roi-c1-1',
    measuredOutcomeId: 'out-c1-1',
    changedAt: '2026-01-15T14:00:00Z',
    changedBy: 'CS AI Lead',
    changeType: 'outcome_recorded',
    newValue: JSON.stringify({ measuredValue: 28, monetizedValue: 1_190_000 }),
    rationale: 'First full-month measurement. 28% deflection — above kill threshold. KB gap constraining ceiling.',
  },
  {
    id: 'audit-c1-4',
    agentId: 'agent-c1',
    roiTargetId: 'roi-c1-1',
    measuredOutcomeId: 'out-c1-2',
    changedAt: '2026-04-10T14:00:00Z',
    changedBy: 'Measurement Analyst',
    changeType: 'outcome_recorded',
    newValue: JSON.stringify({ measuredValue: 31, monetizedValue: 1_317_500 }),
    rationale: 'Q1 FY26 measurement. KB coverage 78%. Improvement trend positive toward 35% target.',
  },
];

// ─── Activity Log Seed Entries ────────────────────────────────────────────────

function act(id: string, agentId: string, timestamp: string, type: ActivityEntry['type'], summary: string, detail?: string, prev?: ActivityEntry['previousStage'], next?: ActivityEntry['newStage']): ActivityEntry {
  return { id, agentId, timestamp, author: 'System', type, summary, detail, previousStage: prev, newStage: next };
}

export const SEED_ACTIVITY_ENTRIES: ActivityEntry[] = [
  act('act-s1-1', 'agent-s1', '2025-01-15T09:00:00Z', 'decision',          'Agent created: AE-001 — AE Prep Agent', 'Stage: idea · Owner: VP Sales GTM'),
  act('act-s1-2', 'agent-s1', '2025-02-10T10:00:00Z', 'stage_change',      'Stage advanced to evaluation', undefined, 'idea', 'evaluation'),
  act('act-s1-3', 'agent-s1', '2025-03-01T14:00:00Z', 'feasibility_update','Feasibility scored: 4.00/5.00', 'Scored by Sales AI Lead'),
  act('act-s1-4', 'agent-s1', '2025-04-05T11:00:00Z', 'stage_change',      'Stage advanced to design', undefined, 'evaluation', 'design'),
  act('act-s1-5', 'agent-s1', '2025-05-15T13:00:00Z', 'stage_change',      'Stage advanced to pilot', undefined, 'design', 'pilot'),
  act('act-s1-6', 'agent-s1', '2025-07-10T14:00:00Z', 'roi_update',        'ROI target created: Prep Time Saved', 'CFO approved'),
  act('act-s1-7', 'agent-s1', '2025-09-01T09:00:00Z', 'stage_change',      'Stage advanced to scale', undefined, 'pilot', 'scale'),
  act('act-s1-8', 'agent-s1', '2025-11-15T16:00:00Z', 'roi_update',        'Outcome recorded: $2.2M monetized value', 'Source: AE Survey + Gong · 48% adoption'),
  act('act-s1-9', 'agent-s1', '2026-01-20T10:00:00Z', 'stage_change',      'Stage advanced to production', undefined, 'scale', 'production'),
  act('act-s1-10','agent-s1', '2026-05-01T16:00:00Z', 'roi_update',        'Outcome recorded: $2.8M monetized value', 'Q1 FY26 · 86% adoption'),

  act('act-c1-1', 'agent-c1', '2025-03-01T09:00:00Z', 'decision',          'Agent created: CS-001 — Smart Case Router', 'Stage: idea · Owner: VP Customer Success'),
  act('act-c1-2', 'agent-c1', '2025-04-10T10:00:00Z', 'stage_change',      'Stage advanced to evaluation', undefined, 'idea', 'evaluation'),
  act('act-c1-3', 'agent-c1', '2025-05-15T14:00:00Z', 'feasibility_update','Feasibility scored: 4.50/5.00', 'Scored by CS AI Architect'),
  act('act-c1-4', 'agent-c1', '2025-06-20T11:00:00Z', 'stage_change',      'Stage advanced to design', undefined, 'evaluation', 'design'),
  act('act-c1-5', 'agent-c1', '2025-08-01T09:00:00Z', 'stage_change',      'Stage advanced to pilot', undefined, 'design', 'pilot'),
  act('act-c1-6', 'agent-c1', '2025-09-10T14:00:00Z', 'roi_update',        'ROI target created: Deflection Rate', 'CFO approved'),
  act('act-c1-7', 'agent-c1', '2025-11-01T13:00:00Z', 'stage_change',      'Stage advanced to production', undefined, 'pilot', 'production'),
  act('act-c1-8', 'agent-c1', '2026-02-15T16:00:00Z', 'roi_update',        'Outcome recorded: $1.5M monetized value', 'Validated by Finance'),
  act('act-c1-9', 'agent-c1', '2026-04-10T14:00:00Z', 'roi_update',        'Outcome recorded: $1.3M monetized value', 'Q1 FY26 measurement'),

  act('act-e1-1', 'agent-e1', '2024-11-01T09:00:00Z', 'decision',          'Agent created: GTM-001 — GTM AI Foundation Platform', 'Stage: design · Owner: GTM AI Lead'),
  act('act-e1-2', 'agent-e1', '2025-01-15T10:00:00Z', 'milestone_update',  'Milestone added: Platform Architecture Sign-off', 'Status: done · Due: 2025-01-15'),
  act('act-e1-3', 'agent-e1', '2025-02-01T11:00:00Z', 'stage_change',      'Stage advanced to pilot', undefined, 'design', 'pilot'),
  act('act-e1-4', 'agent-e1', '2025-03-01T14:00:00Z', 'feasibility_update','Feasibility scored: 3.75/5.00', 'Scored by GTM AI Lead'),
  act('act-e1-5', 'agent-e1', '2025-06-01T09:00:00Z', 'stage_change',      'Stage advanced to production', undefined, 'pilot', 'production'),

  act('act-m1-1', 'agent-m1', '2025-04-01T09:00:00Z', 'decision',          'Agent created: MKT-001 — Intent Signal Scoring', 'Stage: evaluation · Owner: Marketing Ops Lead'),
  act('act-m1-2', 'agent-m1', '2025-05-20T14:00:00Z', 'feasibility_update','Feasibility scored: 3.50/5.00', 'Scored by Marketing AI Lead'),
  act('act-m1-3', 'agent-m1', '2025-07-01T11:00:00Z', 'stage_change',      'Stage advanced to design', undefined, 'evaluation', 'design'),
  act('act-m1-4', 'agent-m1', '2025-09-15T10:00:00Z', 'risk_update',       'Risk logged: Data quality from 3rd-party signal vendors', 'Severity: high · Status: open'),
  act('act-m1-5', 'agent-m1', '2025-10-01T09:00:00Z', 'stage_change',      'Stage advanced to pilot', undefined, 'design', 'pilot'),

  act('act-s2-1', 'agent-s2', '2025-06-01T09:00:00Z', 'decision',          'Agent created: AE-002 — Deal Intelligence Agent', 'Stage: idea · Owner: Sales Strategy'),
  act('act-s2-2', 'agent-s2', '2025-07-10T10:00:00Z', 'stage_change',      'Stage advanced to evaluation', undefined, 'idea', 'evaluation'),
  act('act-s2-3', 'agent-s2', '2025-08-20T14:00:00Z', 'feasibility_update','Feasibility scored: 3.90/5.00', 'Scored by Sales AI Lead'),
  act('act-s2-4', 'agent-s2', '2025-10-01T11:00:00Z', 'stage_change',      'Stage advanced to design', undefined, 'evaluation', 'design'),
  act('act-s2-5', 'agent-s2', '2026-01-15T09:00:00Z', 'stage_change',      'Stage advanced to pilot', undefined, 'design', 'pilot'),
];

// ─── Seed loader ──────────────────────────────────────────────────────────────

export async function loadSeedDataIfEmpty(): Promise<void> {
  const count = await getAgentCount();
  if (count > 0) return;
  await loadSeedData();
}

export async function loadSeedData(): Promise<void> {
  await savePortfolioConfig(SEED_CONFIG);
  await Promise.all(SEED_AGENTS.map(saveAgent));
  await Promise.all(SEED_DATA_FEASIBILITY.map(saveDataFeasibility));
  await Promise.all(SEED_ROI_METHODOLOGIES.map(saveROIMethodology));
  await Promise.all(SEED_ROI_AUDIT_ENTRIES.map(appendROIAuditEntry));
  await Promise.all(SEED_ACTIVITY_ENTRIES.map(appendActivityEntry));
}
